/*
** Minimal vdbe.h stub for SNKV
**
** SNKV uses only the btree -> pager -> os layers of SQLite.
** This stub provides the forward declarations and type definitions
** that sqliteInt.h (from SQLite 3.51.200) expects from vdbe.h,
** without pulling in any actual VDBE implementation.
*/
#ifndef SQLITE_VDBE_H
#define SQLITE_VDBE_H

/* Forward declarations – these are used as pointer types throughout
** sqliteInt.h and btree.h.  The actual struct bodies are never needed
** by the btree/pager/os layer. */
typedef struct Vdbe Vdbe;
typedef struct sqlite3_value Mem;  /* Mem and sqlite3_value are the same type */
typedef struct SubProgram SubProgram;

/*
** VdbeOp – referenced by sqliteInt.h (e.g. in struct Parse).
** Provide a minimal definition so sizeof(VdbeOp) compiles.
*/
typedef struct VdbeOp VdbeOp;
struct VdbeOp {
  u8  opcode;
  signed char p4type;
  u16 p5;
  int p1;
  int p2;
  int p3;
  union p4union {
    int i;
    void *p;
    char *z;
    i64 *pI64;
    double *pReal;
    FuncDef *pFunc;
    sqlite3_context *pCtx;
    CollSeq *pColl;
    Mem *pMem;
    int *ai;
    SubProgram *pProgram;
    Table *pTab;
    KeyInfo *pKeyInfo;
  } p4;
#ifdef SQLITE_ENABLE_EXPLAIN_COMMENTS
  char *zComment;
#endif
#ifdef VDBE_PROFILE
  u32 cnt;
  u64 cycles;
#endif
#ifdef SQLITE_VDBE_COVERAGE
  u32 iSrcLine;
#endif
};

/*
** VdbeOpList – compact op list used by VdbeAddOpList().
*/
typedef struct VdbeOpList VdbeOpList;
struct VdbeOpList {
  u8 opcode;
  signed char p1;
  signed char p2;
  signed char p3;
};

/*
** Opcode definitions from the opcodes header generated by the
** SQLite build process.
*/
#include "opcodes.h"

/*
** RecordCompare – function pointer type used by btree.c for index
** record comparisons (sqlite3BtreeIndexMoveto).
*/
typedef int (*RecordCompare)(int,const void*,UnpackedRecord*);

/*
** Stub prototypes for functions declared in sqliteInt.h that take
** or return Vdbe*.  These will never be called in a btree-only build
** but must exist so the header compiles.
*/
void sqlite3VdbeDelete(Vdbe*);
Vdbe *sqlite3VdbeCreate(Parse*);
int  sqlite3VdbeFinalize(Vdbe*);

/*
** VDBE record-comparison functions used by btree.c for index operations.
** Stub implementations are provided in src/vdbe_stubs.c.
*/
UnpackedRecord *sqlite3VdbeAllocUnpackedRecord(KeyInfo*);
void sqlite3VdbeRecordUnpack(int,const void*,UnpackedRecord*);
RecordCompare sqlite3VdbeFindCompare(UnpackedRecord*);
int sqlite3VdbeRecordCompare(int,const void*,UnpackedRecord*);
void sqlite3MemSetArrayInt64(sqlite3_value*,int,i64);

/*
** VdbeComment macro – normally prints debug comments on opcodes.
** No-op in this stub.
*/
#ifdef SQLITE_DEBUG
  void sqlite3VdbeComment(Vdbe*, const char*, ...);
  void sqlite3VdbeNoopComment(Vdbe*, const char*, ...);
# define VdbeComment(X)      sqlite3VdbeComment X
# define VdbeNoopComment(X)  sqlite3VdbeNoopComment X
# define VdbeModuleComment(X)
#else
# define VdbeComment(X)
# define VdbeNoopComment(X)
# define VdbeModuleComment(X)
#endif

/*
** ADDR macro – converts relative to negative offset for VdbeAddOpList.
*/
#define ADDR(X) (-1-(X))

#endif /* SQLITE_VDBE_H */
